### ISSUE TITLE
Move JSONSchema compilation out of the message loops

### ISSUE THREAD

**Issue by rtyler** [reiseburo/slipstream#1]
Right now slipstream is _super_ inefficient and re-compiles the `JSONSchema` object for each message it receives.

The trick here is that [JSONSchema](https://docs.rs/jsonschema/0.3.0/jsonschema/struct.JSONSchema.html) has a lifetime associated with it, and so pulling it out is likely going to mean that some goofy cross-task management is going to be needed.

My first guess is that I might want to apply similar `dashmap` tactics that I used in [hotdog](/reiseburo/hotdog). :thinking:

**Comment by xianwill** [comment]
@rtyler - i'd like to take this issue from you if you are willing to give it up.
